services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: api_petshop
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres_petshop
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=petshop_db
      - SERVER_PORT=8080
      - JWT_SECRET=chave_secreta_padrao
    depends_on:
      - postgres_petshop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  postgres_petshop:
    image: postgres:17.4-alpine3.21
    container_name: postgres_petshop
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petshop_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_petshop:/var/lib/postgresql/data